-- The 24 September 2026 sitting, added to the running September sitting.
--
-- SOURCE: questions sent by Blesson on 24 Sep 2026, from two examiners. The
-- candidate wrote the first name as "Gadkari"; the bank already carries this
-- examiner as "SS Gadkar" and that spelling is used. Somesh examined alone
-- here, so he gets his own name rather than the combined
-- "Arbind Choudhary / Somesh Prakash" key used for the 18 Sep sitting.
--
-- 26 recollections became 25 cards. Dropped at Blesson's standing instruction:
-- the personal opener (qualifications and sea time). Folded: "ISM codes and
-- certificates" with "ISM and its parts", since they are one answer; "what is
-- open ckt and short ckt" kept separate from "how will you trace it", because
-- the surveyor asked them as two.
--
-- ALL 25 ARE ANSWERED AND PUBLISHED. 12 carry answers written for this sitting
-- (SQ-1099 to SQ-1109 in the bank); 13 reuse bank entries named in ai_flags.
--
-- SAFE TO RUN MORE THAN ONCE: a question is skipped if its text is already
-- recorded for the September sitting on 24 Sep.

begin;

insert into public.exam_questions
  (sitting_id, asked_on, surveyor, question_text, topic, answer_text, sort_order,
   ai_model, ai_flags, ai_confidence, is_published)
select s.id, date '2026-09-24', v.surveyor, v.question_text, v.topic, v.answer_text, v.sort_order,
       v.ai_model, v.ai_flags, 'high', true
  from public.exam_sittings s
 cross join (values
  ('Gadkari', 'Non conformity: what is it, and what makes it major?', 'T16', 'Non Conformity: an observed situation where objective evidence shows that a specified requirement has not been met. Objective evidence is the load bearing phrase. It is not an opinion or a feeling that something is untidy: it is a record, a reading, a photograph or a statement that can be shown to somebody else.
Major Non Conformity: an identifiable deviation that poses a serious threat to the safety of personnel or the ship, or a serious risk to the environment, and that requires immediate corrective action. Also treated as major is the lack of effective and systematic implementation of a requirement of the ISM Code, which is the branch people forget.
The Difference In Practice: one expired fire extinguisher is a non conformity. A whole deck of extinguishers never serviced, with no record that anybody looked, is the systematic failure that makes it major, because the system meant to catch it is not working.
What Follows A Major: immediate corrective action before the ship sails, and it can lead to the Safety Management Certificate or the Document of Compliance being withdrawn or suspended. A major found at a port State inspection can also mean detention.
What Follows An Ordinary One: it is recorded with a root cause, a corrective action and a time limit, then closed out with evidence and verified at the next audit. Treating the symptom and not the cause is what turns the same finding into a repeat one, and a repeat finding is how an auditor decides the system is not working.
Observation: worth having ready as the third term. An observation is a statement of fact that is not a breach of a requirement, made to prevent one developing. It is not a non conformity and it does not need corrective action, although ignoring one across several audits tends to produce a finding eventually.
The ETO Angle: the findings that land on you are PMS jobs signed as done with no reading recorded, test instruments out of calibration, emergency lighting or emergency generator tests missing from the log, and drawings not updated after a modification. All four are systematic rather than physical, which is what makes them majors when the auditor is being strict.', 1, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1105'),
  ('Gadkari', 'SOLAS requirement for the emergency fire pump', 'T15', 'When It Is Needed: on a cargo ship, if a fire in any one compartment could put all the main fire pumps out of action, SOLAS Chapter II-2 Regulation 10 requires another means of supplying water, which is the emergency fire pump. Its details are in the FSS Code, Chapter 12.
Capacity: at least 40 per cent of the total capacity of the fire pumps required, and in any case not less than 25 cubic metres per hour on cargo ships of 2,000 gross tonnage and above, or 15 cubic metres per hour on smaller cargo ships.
Pressure: enough to keep the minimum pressure required at the hydrants while delivering that quantity through the fire main.
Location: outside the space holding the main fire pumps and their power source, so one fire cannot take out both. It is not placed in a category A machinery space.
Power: a diesel engine with its own fuel supply, or an electric motor fed from the emergency switchboard, which is why the emergency generator must be able to run it.
Diesel Drive: it must start readily from cold by hand cranking at temperatures down to 0 degrees C, with heating provided where that is not practicable. A starting arrangement other than hand cranking must be able to start it at least six times in 30 minutes, twice of them in the first 10 minutes. The service fuel tank holds enough for at least 3 hours at full load, with enough more carried outside the category A machinery space for a further 15 hours.
Suction: the pump must be able to take suction in all conditions of list, trim, roll and pitch, so the suction head is kept within its capability.
Testing: run regularly under the SMS, and proved during drills and at survey by delivering water at the required pressure. The ETO looks after the motor, its starter and its emergency supply, and remote starting where fitted.', 2, 'bank', 'answer reused from bank entry SQ-1053'),
  ('Gadkari', 'PLC types', 'T07', 'Reading The Question: he means how they are built, so answer that first and offer the duty classes only if he keeps going.
Compact, Also Called Fixed Or Brick: power supply, CPU and a fixed number of I/O points in one sealed housing. It cannot be expanded beyond a small add-on, so it is bought for the job it will do for life. On board that is the single duty machine: sewage plant, compressor unloading, a refrigeration plant, a hydrophore set.
Modular, Also Called Rack: separate power supply, CPU and I/O cards plugged into a backplane. Cards are added, swapped or upgraded, and a failed card is changed without disturbing the rest. This is the standard engine room machine, the one in the alarm and monitoring cabinets, the boiler control and the IAS.
Distributed, Or Remote I/O: one CPU with I/O racks placed out at the machinery, linked back over a fieldbus such as PROFIBUS or Modbus. The signal is digitised at the machine instead of every pair being run back to a central cabinet, which is what removes hundreds of cable runs from a ship. That saving is the reason it is chosen.
Redundant, Or Hot Standby: two CPUs running the same program in step, one in control and one tracking it, changing over on failure without stopping the process. Cargo control on tankers, propulsion and power management, anywhere a stopped controller means a stopped ship.
Safety PLC: a certified controller built for safety duty, with internal channels that check each other and a defined safe state on any internal fault, certified to a SIL under IEC 61508. Physically separate from the control PLC and usually red. Emergency shutdown, burner management, gas detection, ESD on gas carriers. The point to make is that it is kept separate so a control fault cannot disable the protection.
If He Pushes: nano, micro and large are the same compact and modular split described by I/O count, not different designs. A controller sold as a PAC is a modular PLC with more memory and better communications. What matters at survey is whether a card can be changed from the spares on board, and whether the safety functions sit in their own controller.
The ETO Angle: know which type each of your cabinets is, because it decides what you can do at 0300. A compact PLC with a failed input is a whole unit change. A modular one is a card change, and only if the spare is on board and the program backup is current.', 3, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1109'),
  ('Gadkari', 'ACB: cross questions on maintenance, racking and interlocks', 'T04', 'Contact Inspection: Check main and arcing contacts for wear, pitting, or misalignment, as excessive erosion increases contact resistance and heating risk
Mechanism Servicing: Lubricate and inspect the closing/tripping spring mechanism, ensuring smooth, correct operation and proper spring charging
Insulation Testing: Megger test the breaker in the open position to confirm insulation integrity between phases and to earth
Contact Resistance Testing: Measure micro-ohm contact resistance across closed contacts to detect abnormal resistance indicating wear or poor contact pressure
Protection Trip Testing: Verify trip unit/relay operation via secondary injection testing, and confirm mechanical trip-free operation and correct interlock function
Safety First: Interlocks exist to stop the operator switching under unsafe conditions and to prevent contact with live busbars - never defeat them
Racking Interlock: Prevents racking the breaker in or out while closed, avoiding arcing damage to contacts
Closing Interlock: Prevents closing while the breaker is in an intermediate part-racked position
Door/Panel Interlock: Prevents cubicle access while live parts could be exposed
Earthing Switch Interlock: Prevents closing an earthing switch onto a live busbar and vice versa, avoiding a direct short to earth
Safety Shutters: Automatically cover live busbar spouts when the breaker is withdrawn
Key (Kirk) Interlocking: Ensures only permitted combinations of breakers (e.g. bus-tie arrangements) can be closed, preventing unsafe paralleling', 4, 'bank', 'answer reused from bank entries SQ-0151 + SQ-0154'),
  ('Gadkari', 'MARPOL: the annexes, and cross questions on them', 'T17', 'Reading The Question: name the six annexes in order, then give the certificate for each. The trap is that two of them have no certificate at all, and Annex VI has three documents rather than one. Reciting six annexes and six certificates is wrong twice over.
Annex I, Oil: the IOPP Certificate, the International Oil Pollution Prevention Certificate, for ships of 400 GT and above and oil tankers of 150 GT and above. With it go the Oil Record Book Part I for machinery space operations, Part II for cargo and ballast on a tanker, and the SOPEP.
Annex II, Noxious Liquid Substances in bulk: the NLS Certificate, in full the International Pollution Prevention Certificate for the Carriage of Noxious Liquid Substances in Bulk. A chemical tanker built to the IBC Code carries a Certificate of Fitness instead, which covers the same ground, so say both. The Cargo Record Book and the approved Procedures and Arrangements Manual go with it.
Annex III, Harmful Substances in Packaged Form: no certificate. Compliance runs through the IMDG Code, meaning packing, marking, labelling and documentation. If he pushes, the Document of Compliance for ships carrying dangerous goods is a SOLAS certificate under Regulation II-2/19, not a MARPOL one, and offering it as the Annex III certificate is exactly the slip the question is fishing for.
Annex IV, Sewage: the ISPP Certificate, the International Sewage Pollution Prevention Certificate. Ships of 400 GT and above, or ships certified to carry more than 15 persons.
Annex V, Garbage: no certificate either. What proves compliance is the Garbage Management Plan, the Garbage Record Book and the placards.
Annex VI, Air: three documents. The IAPP Certificate for the ship. The EIAPP Certificate for each diesel engine above 130 kW, issued against the NOx Technical Code and backed by that engine NOx Technical File. And the IEE Certificate, the International Energy Efficiency Certificate, which carries EEDI or EEXI and confirms the SEEMP is on board. Most candidates stop at IAPP.
If He Keeps Going: Annexes I and II are compulsory for any party to MARPOL, while III, IV, V and VI are optional annexes a flag state accedes to separately, which is why they entered force years apart. On retention, the Bunker Delivery Note is kept three years and its sealed sample until the fuel is substantially consumed, in any case not less than twelve months.
The ETO Angle: every certificate here rests on equipment you maintain and can be asked to prove. The 15 ppm alarm and the stopping device for the IOPP, the sewage plant for the ISPP, the incinerator and the oxygen analyser for Annex VI, and the records that show each was tested.', 5, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1099'),
  ('Gadkari', 'Fire control plan: what it shows, and where it is kept', 'T15', 'What It Is: a general arrangement plan required by SOLAS Chapter II-2, showing for each deck the fire control stations, the fire sections enclosed by A class and B class divisions, and the means of fighting and controlling a fire.
What Is On It: the fire detection and alarm systems, the sprinkler and fixed fire extinguishing installations and where their release stations are, the fire main with hydrants, hoses and international shore connection, portable extinguishers by type and position, fire dampers and their controls, the remote stops for fans, pumps and fuel valves, the ventilation system with fan numbers and which section they serve, doors and escape routes, and the fireman outfits and EEBDs.
Where It Is Kept: permanently exhibited on board for the guidance of the officers, and a duplicate set, or a booklet of the same plans, kept in a prominently marked weathertight enclosure outside the deckhouse for the assistance of shore side fire fighting personnel. That outside enclosure is the half of the question people miss, and it is the half a surveyor is usually checking.
The Symbols: the graphical symbols come from IMO Resolution A.952(23), with a legend on the plan itself, so a shore fire brigade reading it for the first time in the dark can use it without knowing the ship.
Language: in the working language of the ship, and if that is not English or French, a translation into one of those has to be included.
Keeping It Right: the plan is kept up to date. If an extinguisher moves, a damper is added or a fan is renumbered during a refit and the plan still shows the old arrangement, the plan is wrong and it is a finding. That is the ETO connection, since detection zones and remote stops change with any modification you carry out.
The Related Document: the fire safety operational booklet, which covers the operational precautions and what the crew does, sits alongside the plan and is sometimes combined with the fire training manual.', 6, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1106'),
  ('Gadkari', 'ISM Code', 'T16', 'Definition: ISM is the International Safety Management Code, made mandatory by SOLAS Chapter IX, providing an international standard for safe ship operation and pollution prevention.
Objectives: Safe practices in ship operation and a safe working environment, assessment of all identified risks with safeguards put in place, and continuous improvement of shore and shipboard safety management skills.
Key Requirements: A documented Safety Management System, a designated safety and environmental protection policy, defined responsibilities and authority, and procedures for emergency preparedness, maintenance and reporting of non conformities, accidents and hazardous occurrences.
Designated Person Ashore: The DPA has direct access to the highest level of management and links the ship to the company, monitoring safety and pollution aspects of each ship.
Master''s Authority: The Code requires the company to state clearly that the Master has overriding authority and responsibility to make decisions for safety and pollution prevention and to request company assistance.
Certification: The company holds a Document of Compliance and each ship a Safety Management Certificate, subject to internal audits and to external audits with interim, initial, intermediate and renewal verification.', 7, 'bank', 'answer reused from bank entry SQ-1010'),
  ('Gadkari', 'Port State Control: what the ETO prepares', 'T18', 'Reading The Question: what you personally prepare before a Port State Control inspection, not what the Master does.
Certificates And Records: the electrical entries in the safety equipment and safety construction records in date and to hand. Emergency generator and emergency fire pump test records. Emergency lighting and battery test records. Insulation resistance readings logged with dates so a trend can be seen. Calibration certificates for the instruments you rely on.
Emergency Systems: emergency generator starts on the first attempt and takes load automatically, fuel and starting batteries in order, the space kept above its minimum temperature, and the starting system never left isolated. Emergency switchboard and its changeover proven. Emergency and low location lighting working on every escape route.
Alarms: general alarm audible everywhere including on deck, engineers alarm, machinery space alarms, and the UMS system with its dead man arrangement.
Detection: fire detection panel with no standing faults, no forgotten disablements, and the disablement record complete and current.
Housekeeping That Gets Noticed: no temporary wiring, no taped joints, junction box covers and glands in place, no missing lamps in the machinery space or on escape routes, navigation lights working with spares on board.
Worth Asking First: which concentrated inspection campaign is running at the time, because that decides where the inspector spends his hour.
Common Finding: an isolation left on the fire panel after cargo work. It is written up immediately.', 8, 'bank', 'answer reused from bank entry SQ-1024'),
  ('Gadkari', 'Lifeboat: type carried, and what is required', 'T21', 'The Usual Answer: a container ship normally carries totally enclosed lifeboats, davit launched, one on each side, each able to take everyone on board.
What SOLAS Requires: on a cargo ship, either lifeboats on each side with capacity for everyone, or one free fall lifeboat at the stern with capacity for everyone (SOLAS Chapter III Regulation 31).
Free Fall: common on bulk carriers and tankers, and fitted to some container ships. The whole boat slides down a ramp at the stern and is launched by its own weight, so it needs no falls and gets clear quickly.
Partially Enclosed: allowed on passenger ships, not on cargo ships. If the surveyor says "semi enclosed", that is what he means by it: a boat with rigid covers at each end and a collapsible canopy over the middle.
Why Totally Enclosed On Cargo Ships: a rigid weathertight canopy protects against fire, weather and capsize, it self rights, and on tankers it carries a water spray and air support system for launching through burning oil.
The ETO''s Part: the boat''s battery and charger, the engine starting circuit, the searchlight and lights, the davit winch motor and limit switches, and the embarkation lighting.', 9, 'bank', 'answer reused from bank entry SQ-1093'),
  ('Somesh Prakash', 'MARPOL annexes and the certificate for each', 'T17', 'Reading The Question: name the six annexes in order, then give the certificate for each. The trap is that two of them have no certificate at all, and Annex VI has three documents rather than one. Reciting six annexes and six certificates is wrong twice over.
Annex I, Oil: the IOPP Certificate, the International Oil Pollution Prevention Certificate, for ships of 400 GT and above and oil tankers of 150 GT and above. With it go the Oil Record Book Part I for machinery space operations, Part II for cargo and ballast on a tanker, and the SOPEP.
Annex II, Noxious Liquid Substances in bulk: the NLS Certificate, in full the International Pollution Prevention Certificate for the Carriage of Noxious Liquid Substances in Bulk. A chemical tanker built to the IBC Code carries a Certificate of Fitness instead, which covers the same ground, so say both. The Cargo Record Book and the approved Procedures and Arrangements Manual go with it.
Annex III, Harmful Substances in Packaged Form: no certificate. Compliance runs through the IMDG Code, meaning packing, marking, labelling and documentation. If he pushes, the Document of Compliance for ships carrying dangerous goods is a SOLAS certificate under Regulation II-2/19, not a MARPOL one, and offering it as the Annex III certificate is exactly the slip the question is fishing for.
Annex IV, Sewage: the ISPP Certificate, the International Sewage Pollution Prevention Certificate. Ships of 400 GT and above, or ships certified to carry more than 15 persons.
Annex V, Garbage: no certificate either. What proves compliance is the Garbage Management Plan, the Garbage Record Book and the placards.
Annex VI, Air: three documents. The IAPP Certificate for the ship. The EIAPP Certificate for each diesel engine above 130 kW, issued against the NOx Technical Code and backed by that engine NOx Technical File. And the IEE Certificate, the International Energy Efficiency Certificate, which carries EEDI or EEXI and confirms the SEEMP is on board. Most candidates stop at IAPP.
If He Keeps Going: Annexes I and II are compulsory for any party to MARPOL, while III, IV, V and VI are optional annexes a flag state accedes to separately, which is why they entered force years apart. On retention, the Bunker Delivery Note is kept three years and its sealed sample until the fuel is substantially consumed, in any case not less than twelve months.
The ETO Angle: every certificate here rests on equipment you maintain and can be asked to prove. The 15 ppm alarm and the stopping device for the IOPP, the sewage plant for the ISPP, the incinerator and the oxygen analyser for Annex VI, and the records that show each was tested.', 10, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1099'),
  ('Somesh Prakash', 'ISM Code: its parts, and its certificates', 'T16', 'What It Is: the International Safety Management Code, made mandatory by SOLAS Chapter IX. It sets an international standard for the safe management and operation of ships and for pollution prevention, and it works by requiring a documented Safety Management System rather than by specifying hardware.
Its Parts: Part A, sections 1 to 12, is implementation. That is the safety and environmental policy, company responsibility and authority, the Designated Person Ashore, master responsibility and authority, resources and personnel, shipboard operations, emergency preparedness, reporting of non conformities and accidents, maintenance of the ship and equipment, documentation, and company verification and review. Part B, sections 13 to 16, is certification and verification. Sixteen sections in total, and knowing the split is the answer to this half of the question.
The Two Certificates: the Document of Compliance is issued to the COMPANY, with a copy kept on board. The Safety Management Certificate is issued to the SHIP. That is the distinction being tested: no ship can hold an SMC unless its company holds a valid DOC covering that type of ship.
How Long They Last: both run five years. The DOC is subject to annual verification, carried out within three months before or after its anniversary date. The SMC gets at least one intermediate verification, and where there is only one it falls between the second and third anniversary date.
The Interim Certificates: an Interim DOC is issued for up to 12 months, for a new company or when a company takes on a ship type it has not operated before. An Interim SMC runs 6 months, extendable by a further 6 in special cases, and covers a newly delivered ship, a change of flag, or a company taking over a ship it did not manage before.
Two Answers Worth Having Ready: the DPA has direct access to the highest level of management, which is what stops a shipboard safety concern being filtered out by middle management. And the master has overriding authority to take any decision for safety and pollution prevention and to request company assistance, which the company must state in writing.
The ETO Angle: an auditor asks you for the planned maintenance records, the critical equipment list and how it is tested, the calibration records for your test instruments, and the record of emergency generator, emergency lighting and steering gear tests. An SMS that says a test happens monthly, against a log showing it did not, is what a finding gets written against.', 11, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1100'),
  ('Somesh Prakash', 'How do you monitor battery trickle charging?', 'T23', 'Reading The Question: he is not asking what trickle charging is. He is asking what you look at and what tells you it has gone wrong, so answer in readings and numbers.
On The Charger Panel: output voltage, charging current, battery voltage, and the charger and battery alarms. A modern charger also shows which mode it is in, boost or float, and that changeover happening on its own is itself something to watch.
The Voltage That Matters: float voltage per cell. A lead acid cell floats at about 2.25 to 2.30 V, so a 12 V battery sits at roughly 13.5 to 13.8 V and a 24 V starting set at about 27 V. A nickel cadmium cell floats at about 1.40 to 1.45 V. Below the band the battery quietly goes flat while looking connected. Above it the battery gasses, uses water and cooks.
The Current Tells You The State: on a healthy float the current settles to a trickle, of the order of a thousandth of the ampere hour capacity, so tens of milliamps on a 50 Ah battery. A current still high hours after a charge means the battery is not accepting it, a cell is failing, or the charger never came out of boost.
Temperature: the correct float voltage falls as the battery warms, by roughly 3 mV per cell per degree C. A hot battery room left on a cold weather setting is how a bank gets gassed dry, so check the room temperature and whether the charger has temperature compensation fitted.
Electrolyte, Lead Acid: level above the plates, topped up with distilled water only, and specific gravity by hydrometer, about 1.240 to 1.280 fully charged.
The Trap, Nickel Cadmium: the specific gravity of a nickel cadmium cell does NOT change with state of charge. It sits around 1.240 to 1.300 charged or discharged, because the electrolyte carries ions and is not consumed by the reaction. A hydrometer therefore tells you nothing about how charged a NiCd bank is, and answering hydrometer for every battery shows you learnt one battery. Judge a NiCd on voltage and on a discharge test.
Physical Checks: terminals clean, tight and greased, no green corrosion, case not bulging or leaking, vent caps clear, no unusual warmth, and the ventilation running, because charging makes hydrogen and it is explosive from about 4 percent in air.
The Proof: the log. Weekly and monthly PMS entries of voltage, current, specific gravity where it means something, and temperature. A surveyor asks to see the trend, because one good reading today proves nothing about a battery that has been drifting for six months.
Why He Asks: these are the emergency generator starting batteries, the emergency lighting and the GMDSS reserve source. They sit doing nothing for months and must work the one time they are wanted, and the only thing between that and a flat battery is somebody reading the charger.', 12, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1101'),
  ('Somesh Prakash', 'Soft starter over star-delta: why choose it', 'T03', 'Soft starters utilise back-to-back thyristors to gradually ramp up the applied voltage from near-zero to full voltage, ensuring smooth acceleration and eliminating the sudden mechanical jerks associated with star-delta starting
Unlike star-delta starters that suffer from severe transient current and torque spikes during the open transition from star to delta, soft starters maintain a continuous power supply without transitional breaks
Soft starters provide precise control over the starting sequence, offering a programmable starting current limit (typically 150-350% of rated current) and adjustable acceleration times to match specific load requirements
Star-delta starting restricts the starting torque to exactly one-third of the Direct-On-Line (DOL) torque, which may be insufficient for accelerating certain heavy loads, whereas soft starters allow for tailored torque performance
Soft starters offer a programmable "soft stop" feature that gradually reduces the applied voltage, preventing mechanical shocks and eliminating issues like water hammer in pumping applications', 13, 'bank', 'answer reused from bank entry Q-0116'),
  ('Somesh Prakash', 'Which motor is used for the turning gear, and what is its stator?', 'T03', 'The Motor: a three phase squirrel cage induction motor, a few kW, driving the flywheel through a worm and a high ratio reduction gearbox. It normally carries a fail safe electromagnetic brake held off electrically, so the brake sets the instant the supply is lost and the engine cannot roll away from you.
The Stator, Since That Is What He Asked: the stationary part, a laminated iron core in the frame carrying three windings spaced 120 degrees apart. Fed from a three phase supply those windings produce a magnetic field that rotates at synchronous speed, Ns equals 120 f divided by P. The rotating field cuts the short circuited bars of the rotor, induces current in them, and the force on those current carrying bars drags the rotor round, always slightly slower than the field. That difference is the slip, and without it there would be no induction and no torque.
Why Squirrel Cage: nothing is fed to the rotor, so there are no brushes or slip rings to maintain in an oily engine room. It is the most rugged machine there is, which suits a motor that sits unused for weeks and then has to work first time.
Where The Torque Comes From: the gearbox, not an exotic motor. The reduction ratio is enormous, so a small motor produces the torque to break a stationary crankshaft away and turn it slowly. A high slip or double cage rotor may be specified where the breakaway load is heavy.
The Starter: direct on line. The motor is small and runs briefly, so there is no reason to limit starting current, and DOL gives full torque from the first instant, which is what breaking away needs. It is reversible, so the starter carries forward and reverse contactors, electrically and mechanically interlocked so both can never close together.
The Interlock He Will Ask About Next: with the turning gear engaged the main engine must not be able to start. A limit switch on the engaged position blocks the starting air and the fuel and lights a turning gear engaged indication in the control room. It is a class requirement, it is in the maker instructions, and it is checked at survey.
How You Would Prove It: with the chief permission and on a dead engine, engage the turning gear and attempt a start. The engine must not turn on air and the indication must show. Then disengage and confirm the interlock releases. Add that you would never prove it the other way round, with the engine live.', 14, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1102'),
  ('Somesh Prakash', 'Difference between Ex i and Ex d', 'T19', 'Ex d (Flameproof): The equipment is housed in a robust enclosure designed to securely contain any internal electrical explosion and prevent the hot gases from escaping to ignite the surrounding hazardous atmosphere
Ex d Applications: It is used for equipment that normally produces sparks or arcs, such as electric motors, junction boxes, and luminaires, typically installed in Zone 1 areas like the cargo pump room or deck
Ex i (Intrinsically Safe): The circuit''s design ensures that its maximum electrical energy (voltage and current) is kept safely below the ignition level of the specific gas mixture, even under multiple fault conditions
Ex i Applications: It is used exclusively for low-power instrumentation circuits, such as tank level gauges, pressure/temperature sensors, and gas detectors, and is the only protection type permitted in Zone 0 (continuous hazard) spaces
Ex i Protection Mechanism: Requires a Zener barrier or galvanic isolator installed in a safe area (like the control room) to strictly limit the energy entering the field circuit in the hazardous zone', 15, 'bank', 'answer reused from bank entry Q-0407'),
  ('Somesh Prakash', 'What is an open circuit and what is a short circuit?', 'T22', 'Open Circuit: a break in the path, so current cannot flow. A blown fuse, a tripped overload contact, a burnt contactor tip, a loose or corroded terminal, a broken core inside insulation that looks perfectly sound, or an open coil.
What An Open Circuit Looks Like: the machine is dead and nothing has tripped, because there was never any excess current. With the supply on, the whole supply voltage appears across the break and zero across everything else in series with it, since no current means no volt drop anywhere else. That is the single most useful fact for finding one.
Short Circuit: two points at different potential joined through a path of almost no resistance, phase to phase or phase to neutral. Current rises to whatever the supply and the cable can deliver, limited only by the impedance of the path.
What A Short Circuit Looks Like: the protection has operated, a fuse blown or a breaker tripped, and there is usually physical evidence with it. Heat, discoloured or melted insulation, blackening in a terminal box, arc marks, the smell.
The Difference That Matters: an open circuit stops the machine and harms nothing. A short circuit is an energy problem, which is the whole reason breaking capacity, discrimination and cable sizing exist. One is an inconvenience, the other is what burns a switchboard.
The Third One He Is Usually Driving At: the earth fault, one live conductor reaching the hull through failed insulation, wetted terminals or a crushed cable. On a ship 440 V system the neutral is insulated, so a single earth fault trips nothing and the machine keeps running. Only the earth fault lamp or meter on the board shows it.
Why That One Is Still Urgent: the system tolerates the first earth fault deliberately, so an essential pump is not lost to one wet gland. The danger is the second. An earth fault on another phase makes the hull the link between two phases, giving a phase to phase short circuit through the ship structure with the full fault level of the board behind it. That is why an earth fault alarm gets traced and cleared, not acknowledged and left for the next watch.', 16, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1103'),
  ('Somesh Prakash', 'How will you trace an open circuit, and how a short circuit?', 'T22', 'Start With Safety, Every Time: chief permission and an electrical isolation permit, isolate, lock off and tag, prove dead with a tester you have first proved on a known live source, and discharge anything that stores energy. On a 440 V board this is not the preamble to the answer, it is the part being marked.
Get The Drawings: the schematic for how the circuit is meant to work, the wiring diagram for where the wires actually run. Tracing without them is guessing with a meter in your hand.
Prove The Instrument: continuity range onto a known short, megger onto a known good circuit. An unproved instrument reports faults that are not there and clears ones that are.
Tracing An Open Circuit: dead circuit, continuity or low ohms range. Check the obvious first, the fuse, the overload contact, the control contacts, the terminal blocks, and above all the last place anybody worked. Then halve the circuit instead of walking it end to end. Test from the supply to a point halfway along: continuity good means the break is downstream, so halve what remains and test again; continuity bad means it is upstream. Five or six tests find a break in a twenty component circuit that would otherwise take twenty.
The Live Alternative, If Permitted: with the supply on, the break shows as full voltage across it and nothing across the rest, so a voltmeter walked along a control circuit finds an open contact quickly. It is live working, and it needs the permission, the gloves and the second man to match.
Tracing A Short Circuit: look before you reach for an instrument. Which protective device operated tells you the section. Then look for the evidence: burnt smell, discoloured insulation, blackening in a box, water or oil ingress, a cable crushed where something was moved or lashed.
Then Megger: isolated, and with electronics, VFD outputs and PLC cards disconnected first, because they do not survive it. 500 V DC on a 440 V circuit. Measure core to core and core to earth, and judge against the last logged reading for that circuit rather than a rule of thumb. The 1 MOhm figure is a floor, not a target: a motor that read 80 MOhm last month and 3 MOhm today is failing even though it passes.
Sectionalise, The Same Halving: disconnect at a convenient junction, megger each half, then each quarter, until only one section still reads low. Same method as the open circuit, and it is what turns an afternoon into twenty minutes.
Splitting Motor From Cable: disconnect the cable at both ends, at the starter and at the motor terminal box. Megger the cable alone, then the motor alone with the star point link removed so each winding is tested on its own. Low on the cable is a cable fault, low on the motor is a winding fault. Low but not zero on a motor is usually moisture, so run the anti condensation heater for 24 to 48 hours and retest, and dry the terminal box before condemning anything. Damp terminal boxes have sent healthy motors ashore.
Finding Which Circuit Has The Earth Fault: read the board indicator to see which phase is down, tell the officer of the watch, then switch off one non essential feeder at a time and watch the indication. When it clears, the fault is on the circuit you just opened. Never leave essential services off to carry on searching, and never start this without the bridge knowing supplies are about to be interrupted.
Finish Properly: readings into the electrical log, defect raised in the PMS, and a note of what you changed. A fault that is fixed and not written down happens again to the next man.', 17, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1104'),
  ('Somesh Prakash', 'Boiler PID: what does each term control, and does it control steam or water?', 'T07', 'Clear The Question Up First: P, I and D do not each control a different thing. They are three ways of acting on the same error, added together to give one output that moves one valve.
What The Drum Level Loop Moves: its output goes to the feedwater regulating valve, so that loop controls water. Steam flow is only measured in it, as the feedforward signal in two and three element control.
What Controls The Steam: a separate loop. The steam pressure controller compares pressure with its set point and changes the firing rate, the fuel valve and the combustion air. More fire makes more steam, so pressure is held by the burner, not by the feed valve.
Proportional, In The Level Loop: acts on the error now. The further the level is from set point, the more the feed valve moves. On its own it settles with a small permanent offset, because some error is needed to hold the valve where the load demands.
Integral, In The Level Loop: acts on the error added up over time. It keeps trimming the valve until the level sits exactly on set point, which removes the offset. Too much of it makes the level hunt, and if the valve saturates the integral winds up.
Derivative, In The Level Loop: acts on how fast the error is changing, which gives damping. On drum level it is normally turned off or set very small: the boiling surface makes the level signal noisy and derivative amplifies noise, and during swell it would drive the valve the wrong way.
Typical Settings: gain about 0.5 to 2, integral (reset) about 60 to 180 seconds, derivative off. Quote your own ship''s settings if asked.
In The Pressure Loop: proportional raises the firing rate in proportion to the pressure droop, integral brings pressure back exactly to set point, and derivative is small or off because the fire has dead time and the signal is noisy.
Do Not Mix Up Three Term With Three Element: three term is P plus I plus D inside one controller. Three element is the drum level scheme using level, steam flow and feedwater flow, which exists because swell and shrink move the level the wrong way for a moment after a load change.', 18, 'bank', 'answer reused from bank entry SQ-1098'),
  ('Somesh Prakash', 'Emergency generator: the SOLAS regulations', 'T20', 'Safety First: The emergency generator is the last line of power for life-safety systems - its automatic start, capacity and independence are strictly regulated
Automatic Start: SOLAS Ch.II-1 requires it to auto-start and supply essential services within 45 seconds of main power failure
Capacity and Duration: Must supply the SOLAS-listed emergency services (emergency lighting, steering gear indication, fire detection/alarm, navigation lights, GMDSS/radio) for the required period (commonly 18 hours cargo ships, 36 hours passenger ships)
Transitional Source: A transitional source (batteries) must supply essential loads for at least 30 minutes while the generator starts
Location: Above the uppermost continuous deck, outside main machinery spaces, readily accessible, with its own independent fuel supply
Starting Independence: Independent starting means not reliant on the main system
Testing: Regular functional and load/blackout testing is mandated to confirm reliable starting and load capability', 19, 'bank', 'answer reused from bank entry SQ-0094'),
  ('Somesh Prakash', 'Lifeboat engine regulations, and the minimum starting temperature', 'T21', 'The Number He Wants: the starting system and any starting aids must start the engine at an ambient temperature of MINUS 15 degrees C within 2 minutes of beginning the starting procedure, unless the Administration decides a different temperature is appropriate for the voyages that ship actually makes. LSA Code 4.4.6.
Engine Type: every lifeboat is powered by a compression ignition engine, so a diesel.
The Fuel Rule: no engine may be used if its fuel has a flashpoint of 43 degrees C or less, closed cup test. That is why a lifeboat engine is never petrol.
Starting Arrangements: either a manual starting system, or a power starting system with TWO independent rechargeable energy sources. Starting aids are provided where needed. Keep the batteries straight, because this is where the cross question goes: the radio battery must NOT be used to start the engine, and where powered ventilation is fitted it must not run off the radio battery either. Starting, radio and searchlight batteries are separate duties, and the Code requires means of recharging all of them.
Running Out Of The Water: the engine must run for not less than 5 minutes after starting from cold with the lifeboat still in its stowed position, out of the water. That is the weekly test you actually carry out, and it is why the boat has a cooling arrangement that works dry for that period.
Speed: at least 6 knots in calm water with full complement and equipment, and at least 2 knots while towing a 25 person liferaft loaded with its full complement.
Fuel Capacity: enough for 24 hours running at 6 knots.
Gearbox: ahead and astern, with the controls at the helmsman position.
The ETO Part: the starting batteries and their charger. Check terminal voltage and the charger on float, terminals clean and greased, electrolyte level where the type has one, the battery secured against capsize, and the date of the last replacement. A lifeboat engine that will not start is almost always a battery, not an engine.
The Weekly And Monthly Drills: engine run weekly, ahead and astern, and the boat swung out and lowered to embarkation level monthly where practicable. Log both, because the log is what the surveyor reads.', 20, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1107'),
  ('Somesh Prakash', 'Alternator checks after shore repair, and overload testing', 'T01', 'Safety First: Confirm insulation and mechanical integrity before energising a shore-repaired alternator
Insulation Resistance and PI: Megger stator/rotor windings and check Polarization Index to confirm dry, sound insulation
Winding Resistance: Measure and compare phase resistances to confirm correct repair/rewind
High-Voltage/Withstand Test: A withstand (hi-pot) test may confirm insulation strength after a rewind
No-Load Test: Run the alternator at rated speed on no load to confirm correct voltage build-up and regulation
On-Load/Parallel Test: Confirm stable operation under load and correct load sharing when paralleled
Documentation: Verify repair certificates and record all test results before returning to service
Regulation: Testing follows class requirements before re-commissioning', 21, 'bank', 'answer reused from bank entry SQ-0840'),
  ('Somesh Prakash', 'International shore connection: draw it and explain the dimensions', 'T15', 'What It Is: a standard flange that lets a shore fire main, or another ship, feed water into this ship''s fire main when her own pumps cannot. One side of the fitting is the standard international flange; the other side is made to suit the ship''s own hydrant and hose coupling.
The Rule: SOLAS Chapter II-2 requires at least one international shore connection on ships of 500 gross tonnage and above, to the specification in the FSS Code.
The Numbers Surveyors Want: outside diameter 178 mm. Inside diameter (bore) 64 mm. Bolt circle diameter 132 mm. Four holes of 19 mm diameter, equally spaced on the bolt circle and slotted to the flange edge. Flange thickness at least 14.5 mm. Supplied with four bolts of 16 mm diameter and 50 mm length, four nuts, eight washers and a gasket.
How To Sketch It: draw a circle 178 across, a 64 bore in the middle, a dashed bolt circle at 132, and four slots of 19 opening to the rim at 90 degrees to each other. Mark the flange thickness 14.5 mm on a side view.
Material And Keeping: steel or equivalent, faced flat on the international side, rated for the fire main pressure. It is kept with its bolts, nuts, washers and gasket together, usually in a marked box, accessible from both sides of the ship near the accommodation or gangway.
Why It Matters: it is checked at every PSC inspection because it is useless if the bolts have gone missing.', 22, 'bank', 'answer reused from bank entry SQ-1091'),
  ('Somesh Prakash', 'Cable types used in the engine room', 'T12', 'Cable Layers: A typical marine cable consists of a conductor, insulation, bedding, armour (for mechanical protection), and an outer sheath
Cable Types: Power cables (XLPE/EPR insulated), control/instrumentation cables (often screened), and fire-resistant cables for essential safety circuits
Standards: Marine cables must carry classification society type approval and meet flame-retardant (and where required fire-resistant) standards
Ordering: Specify voltage rating, conductor size, insulation type, armour type, and required fire performance based on the application and run length
Watertight Penetration: Cable transits through watertight bulkheads/decks use approved cable transit systems (e.g. MCT blocks/glands) that maintain watertight and fire integrity while allowing cable passage', 23, 'bank', 'answer reused from bank entry SQ-0452'),
  ('Somesh Prakash', 'Steering gear cable: core size and insulation requirement', 'T12', 'Safety First: Steering gear is safety-critical, so its supply cables must maintain integrity - fire-resistant cable is used for this essential circuit
Fire-Resistant Cable: The steering gear supply uses fire-resistant cable that maintains circuit integrity during a fire
Regulation: SOLAS Ch.II-1 Reg 29 and Ch.II-2 require the steering supply to remain operable, so fire-resistant cabling is specified
Sizing: Sized for the steering motor full-load current with acceptable voltage drop
Routing: Routed to minimise fire/damage risk, with the two steering circuits separated where practical for redundancy
Separate Circuits: The duplicated steering power units are supplied by separate cables/circuits for redundancy
Construction: Armoured, fire-resistant marine cable with class type approval per IEC 60092', 24, 'bank', 'answer reused from bank entry SQ-0903'),
  ('Somesh Prakash', 'Flame detector: draw it and explain how it works', 'T15', 'What To Draw: a sealed head with a lens or window at the front, behind it the sensing cell or cells, then the signal processing board, and the two or four wire connection back to the fire panel. Show the cone of view spreading from the lens, and label the cone, because the field of view and the distance are what the detector is selected on.
What It Senses: radiation from the flame itself, not heat and not smoke. That is why it is the fastest of the three types and why it works where there is no ceiling to collect smoke.
Ultraviolet Type: responds to the ultraviolet a flame emits, in a band of roughly 185 to 260 nanometres. That band is chosen because the sun energy at those wavelengths is absorbed by the atmosphere, so daylight does not trigger it. UV reacts very fast, in milliseconds, but it is blinded by thick smoke and by oil film or dirt on the window.
Infrared Type: looks at the infrared emitted by hot carbon dioxide in the flame, a narrow band around 4.3 micrometres, and confirms it by the flicker of a real fire, a low frequency of a few hertz. A second channel at a nearby wavelength, around 3.8 micrometres, is used as a reference: the detector compares the two, so a steady hot surface that radiates at both shows no difference and is rejected. IR sees through smoke better than UV.
Combined UV And IR: both cells in one head, and the detector alarms only when both agree. That is the arrangement used where false alarms are expensive, because a welding arc gives UV without the right IR signature and a hot exhaust gives IR without the UV.
Where They Are Fitted: boiler fronts, purifier rooms, main engine areas, helicopter decks, pump rooms, cargo areas on tankers. Anywhere a fire will flame quickly rather than smoulder, and anywhere the space is too large or too draughty for smoke to reach a detector on the deckhead.
What Causes False Alarms: arc welding, direct or reflected sunlight, hot surfaces, lightning and, on some types, halogen lamps. The answer to all of them is siting, the combined type, and keeping the window clean.
Maintenance, The ETO Answer: clean the lens on a schedule, because a filmed over window fails to see rather than failing safe. Test with the manufacturer test lamp or test source at the required interval, confirm the panel shows the right zone and the right address, and log it. Most also self monitor the window and report a fault if it is dirty, which is a point worth making, since it shows why you would not simply trust a quiet detector.
Which Detector Where, If He Widens It: smoke for accommodation and where smouldering comes first, heat for galleys and spaces where smoke or steam is normal, flame for the machinery and cargo spaces above. The three are chosen by what the fire will do first, not by preference.', 25, 'claude-opus-5', 'written for this sitting, in the bank as SQ-1108')
 ) as v(surveyor, question_text, topic, answer_text, sort_order, ai_model, ai_flags)
 where s.id = (select id from public.v_current_exam_sitting)
   and not exists (
         select 1 from public.exam_questions e
          where e.sitting_id = s.id
            and e.asked_on = date '2026-09-24'
            and e.question_text = v.question_text
       );

commit;

-- VERIFY -------------------------------------------------------------------
-- select asked_on, surveyor, count(*),
--        count(*) filter (where answer_text is not null and answer_text <> '') as answered,
--        count(*) filter (where is_published) as published
--   from public.exam_questions
--  where sitting_id = (select id from public.v_current_exam_sitting)
--  group by asked_on, surveyor order by asked_on, surveyor;
--
-- UNDO ---------------------------------------------------------------------
-- delete from public.exam_questions
--  where sitting_id = (select id from public.v_current_exam_sitting)
--    and asked_on = date '2026-09-24';
