-- ── Topic videos, editable from the admin console ───────────────────────────
-- Run once in the Supabase SQL Editor. Safe to re-run.
--
-- The video list used to live in 23 encrypted files under data/Orals/videos/,
-- which meant every new YouTube link needed a decrypt, an edit, a re-encrypt
-- and a deploy. There are 496 entries and only four of them have a URL: the
-- structure was written up front and the videos are being made over time, so
-- this is the one part of the content that genuinely has to be editable
-- without a release.
--
-- The videos stay behind the paywall. Access is enforced by RLS below, using
-- the same rule the app uses for oral content, so moving them out of the
-- encrypted files does not make them public.

CREATE TABLE IF NOT EXISTS public.topic_videos (
  id         UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  topic_id   TEXT        NOT NULL,
  section    TEXT        NOT NULL,
  header     TEXT        NOT NULL,
  url        TEXT        NOT NULL DEFAULT '',
  sort_order INTEGER     NOT NULL DEFAULT 0,
  active     BOOLEAN     NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  updated_by UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  -- Keyed on position within the topic, NOT on section. A section can hold
  -- more than one video: T01's s-brushless already has two, and a unique
  -- constraint on (topic_id, section) silently dropped the second one during
  -- seeding, losing a real video that had a URL.
  UNIQUE (topic_id, sort_order)
);

CREATE INDEX IF NOT EXISTS topic_videos_topic_idx ON public.topic_videos (topic_id, sort_order);

-- ── Who may read a topic's videos ─────────────────────────────────────────
-- Mirrors deriveAccess() in supabase/functions/_shared/entitlements.ts for the
-- oral scope. THESE TWO MUST BE CHANGED TOGETHER: this is the only place the
-- access rule is expressed in SQL, and it exists because RLS cannot call the
-- TypeScript one. A lifetime plan, live oral access, or an unexpired trial.
CREATE OR REPLACE FUNCTION public.can_read_oral()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
     WHERE p.id = auth.uid()
       AND (
            p.subscription_plan = 'lifetime'
         OR p.oral_expires_at > NOW()
         OR (p.trial_started_at IS NOT NULL
             AND p.trial_started_at > NOW() - INTERVAL '3 days')
       )
  );
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;

ALTER TABLE public.topic_videos ENABLE ROW LEVEL SECURITY;

-- T01 is the free preview everywhere else in the app (its notes, quiz and
-- videos are deliberately unencrypted), so its videos stay open too.
DROP POLICY IF EXISTS "Read videos with oral access" ON public.topic_videos;
CREATE POLICY "Read videos with oral access"
  ON public.topic_videos FOR SELECT
  USING (active AND (topic_id = 'T01' OR public.can_read_oral()));

DROP POLICY IF EXISTS "Admins manage videos" ON public.topic_videos;
CREATE POLICY "Admins manage videos"
  ON public.topic_videos FOR ALL
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ── Seed from the existing files ──────────────────────────────────────────
-- ON CONFLICT DO NOTHING so re-running never overwrites a URL an admin has
-- since filled in. The files stay in the repo as the structural record.
INSERT INTO public.topic_videos (topic_id, section, header, url, sort_order) VALUES
  ('T01','s-principle','Working Principle & Construction','',0),
  ('T01','s-placement','Why Alternators Are Not Placed on the Bottom Platform (Tank Top)','',1),
  ('T01','s-excitation','Excitation Systems - All 4 Types','',2),
  ('T01','s-brushless','Brushless Excitation System - Malayalam','https://youtu.be/DT3K793kayM?si=pSLhuOGxALNGhFg5',3),
  ('T01','s-surge-suppress','Surge Suppressor Varistor - Malayalam','https://youtu.be/SHzjhJVSEW4?si=BRvWNDntZOl6upqN',4),
  ('T01','s-brushless','Rotating Diode Open Ckt - Malayalam','https://youtu.be/24-XpfrMHPs?si=zSjbTlqGjyvSQBCd',5),
  ('T01','s-avr','AVR - Automatic Voltage Regulator - Malayalam','https://youtu.be/Teii4Pj-3oo',6),
  ('T01','s-voltage-regulation','Voltage Regulation Calculation Methods','',7),
  ('T01','s-solas','SOLAS Electrical Requirements','',8),
  ('T01','s-synchroscope','Synchroscope - Construction, Working & Paralleling','',9),
  ('T01','s-parallel','Parallel Operation & Load Sharing','',10),
  ('T01','s-protection','Protection & Safeties - Complete List','',11),
  ('T01','s-ocr-idmt','Overcurrent Relay (OCR) & IDMT Characteristics','',12),
  ('T01','s-maint','Maintenance & IR Testing','',13),
  ('T01','s-residual','Residual Magnetism & Field Flashing','',14),
  ('T01','s-blackout','Blackout Test - Full Procedure','',15),
  ('T01','s-undervoltage','Motor on Under-Voltage - Torque Drop','',16),
  ('T01','s-dashpot','Dashpot - How It Works','',17),
  ('T01','s-avr-limiter','Brushless Excitation Chain Safeties','',18),
  ('T01','s-kva-example','kVA vs kW - Numerical Example','',19),
  ('T01','s-winding-clean','Winding Maintenance, Cleaning & Workshop Checks','',20),
  ('T01','s-advanced-topics','Advanced Study Topics','',21),
  ('T01','s-cyber-gen','Cybersecurity - Generator Control Systems (IACS E26/E27)','',22),
  ('T01','s-surveyor-qa','Surveyor Questions & Ideal Answers','',23),
  ('T01','s-quickrev','Quick Revision - Surveyor Frequency Guide','',24),
  ('T02','t2-basics','High Voltage Systems - Basics & Definition','',0),
  ('T02','t2-multiples','Why HV Voltages are Multiples of 1.1 kV','',1),
  ('T02','t2-disadv','HV Advantages & Disadvantages - Complete List','',2),
  ('T02','t2-ner','Neutral Earthing Resistor (NER)','',3),
  ('T02','t2-vcb','HV Switchgear - VCB & SF6','',4),
  ('T02','t2-sf6-full','SF6 Gas - Properties, Hazards & Arc Decomposition','',5),
  ('T02','t2-deadfront','Dead Front Panel - IEC Requirement & Touch Voltage','',6),
  ('T02','t2-msb-safeties','MSB Safeties - Complete 14-Point List','',7),
  ('T02','t2-msb-clearances','MSB Clearances & Rubber Mat Requirements','',8),
  ('T02','t2-busbars','Busbars - Configuration & Colour Coding','',9),
  ('T02','t2-arc','Arc Flash & Arc Blast','',10),
  ('T02','t2-safety','HV Working Procedure - Permit to Work (PTW)','',11),
  ('T02','t2-gloves','HV Insulating Gloves - Class, Colour & Voltage Rating','',12),
  ('T02','t2-glove-rules','HV Glove - Compliance & Storage Rules','',13),
  ('T02','t2-vcb-maint','VCB Maintenance & Rack Out Procedure','',14),
  ('T02','t2-vcb-timing','VCB Timing Test - Diagnostic Interpretation','',15),
  ('T02','t2-ir','HV IR Testing','',16),
  ('T02','t2-ir-formula','IEC Minimum IR Formula - Full Rule & 200% Table','',17),
  ('T02','t2-megger-special','Special Megger Voltage Rules','',18),
  ('T02','t2-irm','Insulation Resistance Monitor (IRM)','',19),
  ('T02','t2-bonding','Tanker Hazardous Zones & Bonding','',20),
  ('T02','t2-shaft','Shaft Earthing System','',21),
  ('T02','t2-streaming','Streaming Current & Cargo Hose IR Test','',22),
  ('T02','t2-hvsc-advanced','High Voltage Shore Connection (HVSC) - IEC/IEEE 80005-1:2019','',23),
  ('T02','s-skin-effect','Skin Effect in HV Conductors','',24),
  ('T02','s-corona-effect','Corona Effect in HV Systems','',25),
  ('T02','s-ct-shorting','CT Shorting Terminals - Why CTs Must Never Be Open-Circuited','',26),
  ('T02','s-pt-fuse-vs-ct','Why PT Has a Fuse but CT Does Not','',27),
  ('T02','s-preferential-trip','Preferential Trip - Automatic Load Shedding','',28),
  ('T02','s-megger-vs-multimeter','Why Megger and Not Multimeter for Insulation Testing','',29),
  ('T02','s-diesel-electric','Diesel-Electric Propulsion System','',30),
  ('T02','s-surveyor-qa','Surveyor Questions & Ideal Answers','',31),
  ('T02','t2-quickrev','Quick Revision - High Voltage Surveyor Frequency Guide','',32),
  ('T03','s3-induction-principle','Induction Motor - Complete Working Principle','',0),
  ('T03','s3-syncspeed','Synchronous Speed - Worked Examples','',1),
  ('T03','s3-slip-detail','Slip - Full Detail','',2),
  ('T03','s3-rmf-extra','Rotating Magnetic Field (RMF) - How It Forms','',3),
  ('T03','s3-startcurrent-qa','Starting Current - Why So High','',4),
  ('T03','s3-startmethods-table','Starting Methods - All Compared','',5),
  ('T03','s3-stardelta-extra','Star-Delta Starting - Suitability & Mathematics','',6),
  ('T03','s3-sd-contactors','Star-Delta - Three Contactors & Interlock','',7),
  ('T03','s3-open-close-trans','Open Transition vs Closed Transition Starting','',8),
  ('T03','s3-autotrans-seq','Autotransformer Starter - Contactor Sequence','',9),
  ('T03','s3-softvfd-detail','Soft Starter & VFD - Full Working Detail','',10),
  ('T03','s3-vfd-cii','VFDs & SEEMP Part III / CII Compliance (2024)','',11),
  ('T03','s3-contactor-overload','Magnetic Contactor & Thermal Overload Relay','',12),
  ('T03','s3-protect','Motor Protection - Complete List with Settings','',13),
  ('T03','s3-hrc-bearing','HRC Fuses & ISO Bearing Codes','',14),
  ('T03','s3-motor-physics','Advanced Motor Physics','',15),
  ('T03','s3-dc-motors','DC Motor Subtypes - All Three Types','',16),
  ('T03','s3-arm-react','Armature Reaction in DC Machines','',17),
  ('T03','s3-wardleonard','Ward-Leonard Speed Control System','',18),
  ('T03','s3-back-emf','Back EMF - Principle and Reversing Switch','',19),
  ('T03','s3-braking','Braking Methods - Regenerative, DC Injection & Others','',20),
  ('T03','s3-sync-detail','Synchronous Motor - Damper Windings, Hunting & Safety','',21),
  ('T03','s3-overheating','Motor Overheating - 8 Causes and Actions','',22),
  ('T03','s3-single-phase','Single Phasing - Effect and Detection','',23),
  ('T03','s3-voltage-sag','Voltage Sag - Definition and Causes','',24),
  ('T03','s3-440v-vs-110v','Why 440V for Motors & 110/220V for Lighting?','',25),
  ('T03','s3-dc-on-ac','DC Motor Connected to AC Supply - Effects','',26),
  ('T03','s3-special-motors','Special Ship Motor Applications','',27),
  ('T03','s3-crane-speed','ER Crane - Speed Control Methods','',28),
  ('T03','s3-woundrotor','Wound-Rotor (Slip-Ring) Induction Motor - Full Detail','',29),
  ('T03','s3-rewind','Motor Checks After Rewinding','',30),
  ('T03','s-motorframe','Motor Frame Number (IEC Standard)','',31),
  ('T03','s-motorchecks','Received Motor Checks & Terminal Identification','',32),
  ('T03','s3-frame-detail','Motor Alignment & Bearing Greasing Procedure','',33),
  ('T03','s3-motor-procurement','Motor Procurement - 14-Point Specification Checklist','',34),
  ('T03','s3-motor-overhaul','Motor Overhauling Procedure - 9 Steps','',35),
  ('T03','s3-hydrophore-auto','Hydrophore Pump - Auto Mode Starter','',36),
  ('T03','s3-troubleshoot','Motor Troubleshooting - Practical Scenarios','',37),
  ('T03','s-surveyor-qa','Surveyor Q&A - Topic 3: Electric Motors (Complete)','',38),
  ('T03','s3-quickrev','Quick Revision - Surveyor Frequency Guide','',39),
  ('T04','s-msb-safeties','MSB Safeties - Complete List (10)','',0),
  ('T04','s-acb-ratings','ACB Ratings - IEC Nameplate Symbols','',1),
  ('T04','s-acb-maint','ACB - Routine Maintenance & Isolation Procedure','',2),
  ('T04','s-hrc-fuses','HRC Fuse Types - Rewirable vs Cartridge vs HRC','',3),
  ('T04','s-diff-relay','Protection Relays - Overload vs OCR vs Differential','',4),
  ('T04','s-overload-test','Overload Test Procedure - Generator OCR','',5),
  ('T04','s-revpower-detail','Reverse Power Relay - Causes, Principle & Testing','',6),
  ('T04','s-pref-detail','Preferential Trip - Stage Details & Dashpot','',7),
  ('T04','s-dielectric','Dielectric Strength - ACB vs VCB vs SF₆','',8),
  ('T04','s-pi-physics','PI Test - Why 10 Minutes (3-Component Current)','',9),
  ('T04','s-battery-sg','Battery SG Thresholds & Testing Procedure','',10),
  ('T04','s-ups','UPS - Uninterruptible Power Supply','',11),
  ('T04','s-mcc-detail','Group Starter Panel (MCC) - Unit Contents & IEC Lamp Codes','',12),
  ('T04','s-esb-location','Emergency Switchboard - SOLAS II-1/Reg 42 Location','',13),
  ('T04','s4-msb-esb-interlock','MSB–ESB Electrical Interlock','',14),
  ('T04','s-emerg-autostart','Emergency Generator - Auto-Start Sequence & SOLAS Requirements','',15),
  ('T04','s4-pms','Power Management System (PMS)','',16),
  ('T04','s4-earth-fault-proc','Earth Fault - Detection & Investigation Procedure','',17),
  ('T04','s4-isolated-neutral-v','Isolated Neutral System - Phase-to-Earth Voltage','',18),
  ('T04','s-fire-detector','Fire Detector - SC vs OC vs Fire Alarm (EOL Circuit)','',19),
  ('T04','s-msb-survey','MSB Survey Preparation - 14-Point Checklist','',20),
  ('T04','s-surveyor-qa','Surveyor Q&A - Oral Exam Drills','',21),
  ('T04','s-quickrev','Quick Revision - Surveyor Frequency Guide','',22),
  ('T05','s-principle','1. Working Principle & EMF Equation','',0),
  ('T05','s-losses','2. Iron (Core) & Copper (Winding) Losses','',1),
  ('T05','s-noload','3. No-Load vs On-Load Behaviour','',2),
  ('T05','s-hum','4. Transformer Hum - Causes & Action','',3),
  ('T05','s-kva-rating','5. Why Transformers & Alternators Are Rated in kVA - Not kW','',4),
  ('T05','s-dc-supply','6. What Happens When DC Is Applied to a Transformer Primary','',5),
  ('T05','s-frequency-compat','7. Operating a Transformer at Different Frequencies','',6),
  ('T05','s-auto','8. Auto-Transformer vs Double-Wound Transformer','',7),
  ('T05','s-ctpt','9. Current Transformer (CT) & Potential Transformer (PT)','',8),
  ('T05','s-ct-knee','10. CT Knee Point - Saturation & Protection CT Specification','',9),
  ('T05','s-buchholz','11. Buchholz Relay - Transformer Protection','',10),
  ('T05','s-oil','12. Transformer Oil - Specifications & Testing','',11),
  ('T05','s-coolingmethods','13. Cooling Methods - ONAN, ONAF, OFAF','',12),
  ('T05','s-parallel','14. Parallel Operation of Transformers - Conditions','',13),
  ('T05','s-3phase-banks','Three Single-Phase Transformer Banks & CT Accuracy Class','',14),
  ('T05','s-tests','15. Open Circuit (OC) & Short Circuit (SC) Tests','',15),
  ('T05','s-flyback','16. Flyback Transformer - SMPS & Power Electronics','',16),
  ('T05','s-lvdt','17. LVDT - Linear Variable Differential Transformer','',17),
  ('T05','s-msb-interlock','18. Mechanical Interlock for Transformer / Bus Sources at MSB','',18),
  ('T05','s-surveyorqa','19. Surveyor Questions & Ideal Answers','',19),
  ('T05','s-quickrev','20. Quick Revision - Surveyor Frequency Guide','',20),
  ('T06','s-temp','RTD vs Thermocouple - Principles, Types & CJC','',0),
  ('T06','s-thermowell','Thermowell - Purpose, Resonance & Failure','',1),
  ('T06','s-loop','4-20mA Signal, Smart Transmitter & HART Protocol','',2),
  ('T06','s-intrinsic','Intrinsic Safety - Zener Barrier vs Galvanic Isolator','',3),
  ('T06','s-sipart','SIPART PS2 Positioner - Function & Calibration','',4),
  ('T06','s-dp','DP Transmitter - Capsule, Manifold & Zero Suppression','',5),
  ('T06','s-flowmeters','Flowmeters - Coriolis, Turbine, Vortex & Orifice','',6),
  ('T06','s-analyzers','Analysers - O₂, Salinometer, Viscotherm & Exhaust Gas','',7),
  ('T06','s-proximity','Proximity Sensors - Inductive, Capacitive & Others','',8),
  ('T06','s-magpickup','Magnetic Pick-Up & Electric Tachometers','',9),
  ('T06','s-modbus','Modbus Communication Protocol','',10),
  ('T06','s-megger','Megger Test, Insulation Resistance & PI Test','',11),
  ('T06','s-ums','UMS Alarm System & Pressure Transmitter Calibration','',12),
  ('T06','s-calibration','Calibration Traceability - Standards & Certification','',13),
  ('T06','s-level','Level Sensors - Float, Capacitance, Ultrasonic, Radar','',14),
  ('T06','s-straingauge','Strain Gauge, Wheatstone Bridge & LVDT','',15),
  ('T06','s-gasdetect','Gas Detectors - Pellistor, NDIR, PID & Electrochemical','',16),
  ('T06','s-surveyorqa','Surveyor Questions & Ideal Answers','',17),
  ('T06','s-quickrev','Quick Revision - Surveyor Frequency Guide','',18),
  ('T07','s-openclosed','1. Open Loop vs Closed Loop Control','',0),
  ('T07','s-pid','2. PID Controller - P, I, D Actions','',1),
  ('T07','s-feedforward','3. Feedforward Control vs Feedback Control','',2),
  ('T07','s-cascade','4. Cascade Control System','',3),
  ('T07','s-plc','5. PLC & Ladder Diagram','',4),
  ('T07','s-plc-hardware','6. PLC Hardware Modules','',5),
  ('T07','s-timers','7. PLC Timers & Counters','',6),
  ('T07','s-systems','8. Specific Ship Control Systems','',7),
  ('T07','s-pms','9. PMS & Power Management','',8),
  ('T07','s-preferential-trip','10. Preferential Trip & Self-Monitoring Alarms','',9),
  ('T07','s-valves','11. Control Valves & I/P Converters','',10),
  ('T07','s-valve-positioner','12. Valve Positioner - Physics & Correction','',11),
  ('T07','s-ias-scada','13. IAS / SCADA Architecture','',12),
  ('T07','s-fieldbus','14. Fieldbus Protocols - Modbus vs PROFIBUS vs PROFINET vs HART','',13),
  ('T07','s-gap','15. Additional Topics','',14),
  ('T07','s-plc-noise','16. PLC Noise Protection & Battery Replacement','',15),
  ('T07','s-cyber','17. IACS UR E26/E27 - Maritime Cybersecurity (Mandatory 2024)','',16),
  ('T07','s-surveyorqa','Surveyor Questions & Ideal Answers','',17),
  ('T07','s-quickrev','Quick Revision - Surveyor Frequency Guide','',18),
  ('T08','s-diodes','1. P-N Junction Diode & Zener Diode','',0),
  ('T08','s-rectifiers','2. Rectifiers & Ripple Factor','',1),
  ('T08','s-transistors','3. Transistors - BJT & MOSFET','',2),
  ('T08','s-thyristors','4. Thyristor (SCR) & IGBT','',3),
  ('T08','s-transistor-matrix','5. Power Transistor Comparison - BJT vs MOSFET vs IGBT vs SCR','',4),
  ('T08','s-cyclo','6. Cycloconverter','',5),
  ('T08','s-synchroconv','7. Synchroconverter (Line-Commutated Drive)','',6),
  ('T08','s-opto','8. Optocouplers & Commutators','',7),
  ('T08','s-amplifiers','9. Amplifier Classes & Op-Amps','',8),
  ('T08','s-grid-bias','10. Grid Bias Voltage','',9),
  ('T08','s-opamp-iv','11. Operational Amplifier (Op-Amp) & I/V Converter','',10),
  ('T08','s-digital','12. Logic Gates, Digital System & D/A Resolution','',11),
  ('T08','s-smps','13. Switch Mode Power Supply (SMPS)','',12),
  ('T08','s-vfd-igbt','14. VFD with IGBT - Operation, PWM & Motor Impact','',13),
  ('T08','s-hall-effect','15. Hall Effect Sensor','',14),
  ('T08','s-pwm-harmonics','16. PWM Harmonics & Effect on Motor Insulation','',15),
  ('T08','s-protection-diodes','17. Protection Diodes - TVS, Schottky & Flyback','',16),
  ('T08','s-ex-zones','18. Hazardous Area Equipment (Ex Zones)','',17),
  ('T08','s-is-entity','19. Intrinsic Safety - Entity Concept & Fault Tolerance','',18),
  ('T08','s-emf-pd','20. EMF vs Potential Difference','',19),
  ('T08','s-components','21. Additional Components & Properties','',20),
  ('T08','s-diode-apps','22. Shipboard Diode Applications','',21),
  ('T08','s-megger-ir','23. Insulation Resistance Testing (Megger)','',22),
  ('T08','s-avr-circuit','24. AVR Electronic Control Circuit','',23),
  ('T08','s-rot-diode-fail','25. Rotating Rectifier Diode Failure Effects','',24),
  ('T08','s-electronics-formulae','26. Key Electronics Formulae','',25),
  ('T08','s-cap-res-test','26. Capacitor & Resistor Testing','',26),
  ('T08','s-surveyorqa','Surveyor Questions & Ideal Answers','',27),
  ('T08','s-quickrev','Quick Revision - Surveyor Frequency Guide','',28),
  ('T09','s-omd','Oil Mist Detector (OMD)','',0),
  ('T09','s-crankcase-relief','Crankcase Explosion - Relief Valves & Shutdown Logic','',1),
  ('T09','s-visco','Viscosity Controller (Viscotherm)','',2),
  ('T09','s-steering','Steering Gear (Electrical Systems)','',3),
  ('T09','s-steering-alarms','Steering Gear Alarms & Trips','',4),
  ('T09','s-steering-isolation','Steering Gear - Automatic Isolation & Alarm System','',5),
  ('T09','s-boiler','Boiler BMS - Burner Management System','',6),
  ('T09','s-boiler-alarms','Boiler Electrical Alarms & ETO Troubleshooting','',7),
  ('T09','s-boiler-level','Boiler Water Level Control - 1, 2 & 3-Element','',8),
  ('T09','s-jcw','Jacket Cooling Water (JCW) Automation','',9),
  ('T09','s-embrake','Electromagnetic (EM) Brake - Crane & Windlass','',10),
  ('T09','s-thruster','Bow Thruster - Interlocks & Protection','',11),
  ('T09','s-cpp','CPP (Controllable Pitch Propeller) - Electrical Systems','',12),
  ('T09','s-purifier','Purifier (Separator) - Electrical Aspects','',13),
  ('T09','s-purifier-start','Purifier Motor Starting - Centrifugal Clutch & OC Relay Bypass','',14),
  ('T09','s-reefer','Refrigeration - LP/HP Cutouts & Oil Differential','',15),
  ('T09','s-reefer-types','Refrigeration - Evaporator Types: Dry Expansion vs Flooded','',16),
  ('T09','s-reefer-lo','Reefer Compressor LO Pressure Sensor Calibration','',17),
  ('T09','s-tev','TEV - Thermostatic Expansion Valve','',18),
  ('T09','s-ac-rating','Air-Conditioning - Capacity in Tons & Humidifier Working','',19),
  ('T09','s-engine','Main Engine - Slow-Down vs Trip','',20),
  ('T09','s-dashpot-gov','Dashpot - Governor Hunting & ACB Inverse-Time','',21),
  ('T09','s-gov-types','Governor Types','',22),
  ('T09','s-overspeed-test','Overspeed Relay Test Procedure','',23),
  ('T09','s-lo-alarm','Lube Oil Low Pressure Alarm - ETO Action','',24),
  ('T09','s-tc-rpm','Turbocharger RPM Sensor','',25),
  ('T09','s-aircomp','Air Compressor - Auto Start/Stop & Charging Regulations','',26),
  ('T09','s-windlass','Windlass & Mooring Winch - Electrical Systems','',27),
  ('T09','s-autotension','Auto-Tension Mooring Winch','',28),
  ('T09','s-crane-safeties','Crane Safeties - ALL Types','',29),
  ('T09','s-crane-speed','ER Crane - Speed Adjustment','',30),
  ('T09','s-cargo-pump','Cargo Pump Motor - Deep-Well & Hydraulic Types','',31),
  ('T09','s-stern-tube','Stern Tube Seal Heating - Purpose, Thermostat & Alarm','',32),
  ('T09','s-pumproom','Pump Room Entry Safety & Fan Interlock','',33),
  ('T09','s-ows','OWS - Oil/Water Separator & 15 ppm Monitoring','',34),
  ('T09','s-smoke-density','Smoke Density Meter','',35),
  ('T09','s-salinometer','Salinometer & Fresh Water Generator','',36),
  ('T09','s-antiheeling','Anti-Heeling System','',37),
  ('T09','s-bilge-inj','Bilge Injection Valve','',38),
  ('T09','s-deadship','Dead Ship Recovery - Manual Sequence','',39),
  ('T09','s-ums-prearrival','UMS Pre-Arrival Verification - 8-Step Protocol','',40),
  ('T09','s-drydock','Drydock Duties & Working Aloft','',41),
  ('T09','s-lifeboat-air','Air Bottle in Lifeboat / Sprinkler System','',42),
  ('T09','s-lifting2026','New 2026 - Lifting Appliances Regulation (SOLAS II-1/3-13)','',43),
  ('T09','s-surveyorqa','Surveyor Q&A - Topic 9','',44),
  ('T09','s-galley-oven','Galley Electric Oven - Circuit & ETO Responsibilities','',45),
  ('T09','s-fo-leakoff','Fuel Oil Leak-Off System & Alarm','',46),
  ('T09','s-quickrev','Quick Revision - Topic 9 Frequency Guide','',47),
  ('T10','s-principle','Cathodic Protection - Principle','',0),
  ('T10','s-types','Types of Cathodic Protection','',1),
  ('T10','s-potentials','Protection Potentials & Key Values','',2),
  ('T10','s-electrodes','Reference Electrode Types','',3),
  ('T10','s-comparison','ICCP vs Sacrificial Anodes - Full Comparison','',4),
  ('T10','s-operation','ICCP System Operation','',5),
  ('T10','s-coatings','Coating Systems & Cathodic Disbondment','',6),
  ('T10','s-stray','Stray Current Corrosion at Berth','',7),
  ('T10','s-faults','ICCP Fault-Finding','',8),
  ('T10','s-bonding','Electrical Bonding','',9),
  ('T10','s-shaft-detail','Shaft Earthing Brush - Specifications & Testing','',10),
  ('T10','s-mgps','MGPS - Marine Growth Prevention System (Basic)','',11),
  ('T10','s-mgps-detail','MGPS - Full Technical Details','',12),
  ('T10','s-drydock','Dry Dock Maintenance','',13),
  ('T10','s-commissioning','Drydock Re-commissioning Procedure','',14),
  ('T10','s-advanced','Advanced Notes - Surveyor Technical Questions','',15),
  ('T10','s-surveyorqa','Surveyor Q&A - Topic 10','',16),
  ('T10','s-quickrev','Quick Revision - Topic 10','',17),
  ('T11','s-triangle','Power Triangle - Foundations','',0),
  ('T11','s-kva','Why Alternator is Rated in kVA, Not kW','',1),
  ('T11','s-reactive','Reactive Power - Where Does It Go?','',2),
  ('T11','s-lowpf','Effects of Low Power Factor on Ships','',3),
  ('T11','s-pf-load','Power Factor at Different Load Levels','',4),
  ('T11','s-correction','Power Factor Correction - Methods & Comparison','',5),
  ('T11','s-sync-start','Synchronous Motor - Why Cannot Self-Start & Starting Methods','',6),
  ('T11','s-droop','Droop - Governor & AVR Droop for Parallel Operation','',7),
  ('T11','s-lossexcitation','Loss of Excitation During Parallel Operation','',8),
  ('T11','s-avrsolas','AVR - SOLAS Regulation & Function','',9),
  ('T11','s-harmonics','Harmonics, THD & Sources','',10),
  ('T11','s-notching','Voltage Notching - Thyristor Drive Effect','',11),
  ('T11','s-harmonic-filters','Harmonic Filters - Passive vs Active','',12),
  ('T11','s-kfactor','K-Factor Transformers - Derating for Harmonic Loads','',13),
  ('T11','s-formfactor','Form Factor & Crest Factor','',14),
  ('T11','s-preftrip','Preferential Trip System','',15),
  ('T11','s-shorepower','Shore Power Connection (Cold Ironing)','',16),
  ('T11','s-kirchhoff','Kirchhoff''s Laws - Marine Applications','',17),
  ('T11','s-surveyorqa','Surveyor Q&A - Topic 11','',18),
  ('T11','s-quickrev','Quick Revision - Topic 11','',19),
  ('T12','s-layers','Cable Construction - Layers','',0),
  ('T12','s-cable-types','Cable Insulation Materials - XLPE, EPR, PVC & LSZH Sheathing','',1),
  ('T12','s-screening','Cable Screening & Shielding','',2),
  ('T12','s-standards','IEC Cable Standards - Complete Reference','',3),
  ('T12','s-insclass','Insulation Classes - Temperature Limits','',4),
  ('T12','s-selection','Cable Selection - How to Specify & Order','',5),
  ('T12','s-neutral','Insulated Neutral (IT) System','',6),
  ('T12','s-megger','Megger IR Test - Full Procedure','',7),
  ('T12','s-pi','Polarisation Index (PI) Test','',8),
  ('T12','s-fault-location','Cable Fault Location Methods','',9),
  ('T12','s-vfd-cable','VFD Cables - Special Requirements','',10),
  ('T12','s-trace-heat','Trace Heating Cables','',11),
  ('T12','s-penetrations','Bulkhead Penetrations & Busbar Thermography','',12),
  ('T12','s-surveyorqa','Surveyor Q&A - Topic 12','',13),
  ('T12','s-quickrev','Quick Revision - Topic 12','',14),
  ('T13','s-radar','RADAR - Working Principle & Bands','',0),
  ('T13','s-radar-full','RADAR - Full Technical Detail & ARPA','',1),
  ('T13','s-solidstate','Solid State RADAR - Magnetron vs Solid State','',2),
  ('T13','s-gmdss','GMDSS - Equipment & Sea Areas','',3),
  ('T13','s-gmdss-full','GMDSS - Complete Equipment Technical Detail','',4),
  ('T13','s-gmdss-2024','2024 GMDSS Regulatory Modernisation','',5),
  ('T13','s-epirb','EPIRB - Working & Specifications','',6),
  ('T13','s-sart','SART - Search & Rescue Transponder','',7),
  ('T13','s-epirb-sart-full','EPIRB & SART - Side-by-Side Technical Comparison','',8),
  ('T13','s-vhf','VHF & NAVTEX','',9),
  ('T13','s-inmarsat','Inmarsat C vs Fleet Broadband - SafetyNET MSI','',10),
  ('T13','s-battery','GMDSS Battery - Load Test Procedure','',11),
  ('T13','s-ais','AIS - Class A vs Class B','',12),
  ('T13','s-doppler','Doppler Speed Log & EM Log - Comparison','',13),
  ('T13','s-echosounder','Echo Sounder - Piezoelectric Working','',14),
  ('T13','s-gyro','Gyrocompass - Principles & ETO Maintenance','',15),
  ('T13','s-fluxgate','Fluxgate Compass - Working Principle & Role','',16),
  ('T13','s-bnwas','BNWAS, VDR & SSAS','',17),
  ('T13','s-navlights','Navigation Lights - COLREG Arcs & BITT','',18),
  ('T13','s-steeringmodes','Steering Control Modes - FU vs NFU','',19),
  ('T13','s-surveyorqa','Surveyor Q&A - Topic 13','',20),
  ('T13','s-quickrev','Quick Revision - Topic 13','',21),
  ('T14','s-gas-detection','Gas Detection - Explosimeter vs Tankscope','',0),
  ('T14','s-o2-analyser','Oxygen Analyser - Paramagnetic & Electrochemical Types','',1),
  ('T14','s-toxic-gas','Toxic Gas Detectors - H₂S and CO','',2),
  ('T14','s-gas-calibration','Portable Gas Detector Calibration - Bump Test vs Full Calibration','',3),
  ('T14','s-cargo-gauging','UTI Devices, Intrinsic Safety & Remote Cargo Gauging','',4),
  ('T14','s-cargo-computer','Cargo Computer / Loading Instrument','',5),
  ('T14','s-ecdis-widas','ECDIS, WIDAS & Emergency Steering','',6),
  ('T14','s-solas-2026','2026 SOLAS Amendments - Electronic Inclinometers & Container Loss','',7),
  ('T14','s-surveyorqa','Surveyor Q&A - Topic 14','',8),
  ('T14','s-quickrev','Quick Revision - Topic 14','',9),
  ('T15','s-classes','Fire Classes, Tetrahedron & Extinguishers','',0),
  ('T15','s-fire-divisions','Structural Fire Divisions - A-Class, B-Class, C-Class','',1),
  ('T15','s-co2','Fixed CO2 Total Flooding System','',2),
  ('T15','s-co2-maint','CO2 System Maintenance - Bulk LP System','',3),
  ('T15','s-foam','Fixed Foam Systems','',4),
  ('T15','s-clean-agents','Clean Agent & Inert Gas Suppression Systems','',5),
  ('T15','s-halon','Halon - History & Phase-Out','',6),
  ('T15','s-sprinkler','Automatic Sprinkler System','',7),
  ('T15','s-watermist','High-Pressure Water Mist System (Hi-Fog)','',8),
  ('T15','s-detection','Fire Detection - Types & Working Principles','',9),
  ('T15','s-fire-panel','Fire Alarm Panel - Zone Wiring, EOL & Self-Test','',10),
  ('T15','s-testing','Fire Detector Testing Procedures','',11),
  ('T15','s-pumps','Fire Pumps - SOLAS Requirements','',12),
  ('T15','s-hold-roro','Cargo Hold Fires & 2026 Ro-Ro Overhaul','',13),
  ('T15','s-ba-search','BA Team Search in Smoke-Filled Accommodation','',14),
  ('T15','s-surveyorqa','Surveyor Q&A - Topic 15','',15),
  ('T15','s-quickrev','Quick Revision - Topic 15','',16),
  ('T16','s-solas-overview','SOLAS - Overview & All Chapters','',0),
  ('T16','s-ch2','SOLAS Chapter II-1 - Electrical Installations (Part D)','',1),
  ('T16','s-empower','Emergency Source of Electrical Power (Regulation 42/43)','',2),
  ('T16','s-cables','Cable Requirements (Regulation 45)','',3),
  ('T16','s-survey-checks','Class Special Electrical Survey - Mandated Protocols','',4),
  ('T16','s-ch22','SOLAS Chapter II-2 - Fire Protection, Detection & Extinction','',5),
  ('T16','s-ch3','SOLAS Chapter III - Life-Saving Appliances (LSA)','',6),
  ('T16','s-ch4','SOLAS Chapter IV - GMDSS (Radio Communications)','',7),
  ('T16','s-ch5','SOLAS Chapter V - Safety of Navigation','',8),
  ('T16','s-ch6-7','SOLAS Chapters VI & VII - Cargo & Dangerous Goods','',9),
  ('T16','s-loadline','Load Line Convention - Freeboard & Plimsoll Line','',10),
  ('T16','s-colregs','COLREGS - Collision Regulations (Basic ETO Awareness)','',11),
  ('T16','s-ism','ISM Code - Safety Management & Audit Architecture (SOLAS Chapter IX)','',12),
  ('T16','s-classflag','Class Society vs Flag State vs Port State - Who Does What?','',13),
  ('T16','s-isps','ISPS Code - Maritime Security Controls (SOLAS XI-2)','',14),
  ('T16','s-conventions','International Conventions - MLC 2006 & STCW','',15),
  ('T16','s-enclosedspace','Enclosed Space Gas Limits & Entry Permits','',16),
  ('T16','s-new2026','New 2026 SOLAS Regulations','',17),
  ('T16','s-surveyorqa','Surveyor Q&A - Topic 16','',18),
  ('T16','s-quickrev','Quick Revision - Topic 16','',19),
  ('T17','s-annexI','MARPOL Annex I - Oil Pollution Prevention','',0),
  ('T17','s-iopp','IOPP Certificate & Port State Control (PSC)','',1),
  ('T17','s-orb','Oil Record Book (ORB)','',2),
  ('T17','s-annexII','MARPOL Annex II - Noxious Liquid Substances (NLS)','',3),
  ('T17','s-annexIII','MARPOL Annex III - Harmful Substances in Packaged Form','',4),
  ('T17','s-annexIV','MARPOL Annex IV - Prevention of Pollution by Sewage','',5),
  ('T17','s-annexV','MARPOL Annex V - Prevention of Pollution by Garbage','',6),
  ('T17','s-bwmc','Ballast Water Management Convention (BWMC)','',7),
  ('T17','s-annexVI','MARPOL Annex VI - Air Pollution Prevention','',8),
  ('T17','s-cii','CII, SEEMP & Energy Efficiency','',9),
  ('T17','s-carbonstrategy','IMO 2023 GHG Strategy - Carbon Levy & 2030/2050 Targets','',10),
  ('T17','s-altfuels','Alternative Fuels & IGF Code - 2026 Updates','',11),
  ('T17','s-new2024','2024–2026 Regulatory Updates - Know These','',12),
  ('T17','s-surveyorqa','Surveyor Q&A - Topic 17','',13),
  ('T17','s-quickrev','Quick Revision - Topic 17','',14),
  ('T18','s-surveytypes','1. Survey Types - Annual, Intermediate, Special & Continuous','',0),
  ('T18','s-preparation','2. Complete Electrical Survey - Preparation & Documents','',1),
  ('T18','s-msb','3. MSB Survey - Dead Front Panel & MSB Safeties','',2),
  ('T18','s-acb','4. ACB Survey - Trip Tests, UVT Coil & Isolation','',3),
  ('T18','s-overspeed','5. Overspeed Trip Test - DG and Main Engine','',4),
  ('T18','s-rpr','6. Reverse Power Trip - Construction & Working','',5),
  ('T18','s-mechecks','7. Main Engine Checks During Electrical Survey','',6),
  ('T18','s-shoresupply','8. Emergency Shore Supply During Drydock','',7),
  ('T18','s-battery','9. Battery Capacity Test - Discharge Procedure & Acceptance Criteria','',8),
  ('T18','s-navlights','10. Navigation Light Survey - Test Procedure & Certificate','',9),
  ('T18','s-crane','11. Crane & Elevator Electrical Survey - Class Requirements','',10),
  ('T18','s-emgfirepump','12. Emergency Fire Pump - Annual SOLAS Test','',11),
  ('T18','s-ism','13. ISM Code & SMS - ETO Duties','',12),
  ('T18','s-ptw','14. Permit to Work (PTW) System','',13),
  ('T18','s-survey','15. Electrical Survey - Full Physical Test Checklist','',14),
  ('T18','s-shore-sync','16. Shore Power - Phase-Sequence & Trapped-Key Safeties','',15),
  ('T18','s-droptest','17. Drop Test (Millivolt-Drop) - Busbar & Breaker Contact Resistance','',16),
  ('T18','s-surveyorqa','Surveyor Questions & Ideal Answers','',17),
  ('T18','s-quickrev','Quick Revision - Surveyor Frequency Guide','',18),
  ('T19','s-zones','1. Hazardous Area Zone Classification (IEC 60079-10-1)','',0),
  ('T19','s-exprotection','2. Explosion-Protected (Ex) Equipment - All Types','',1),
  ('T19','s-atex-label','3. ATEX Certification Label Reading','',2),
  ('T19','s-ex-inspection','4. Ex Equipment Inspection (IEC 60079-17)','',3),
  ('T19','s-deck','5. Tanker Deck Electrical System','',4),
  ('T19','s-igsystem','6. Inert Gas (IG) System - Safeties, Trips & Complete Pressure Cascade','',5),
  ('T19','s-cargo-heating','7. Cargo Heating System','',6),
  ('T19','s-bowthruster','8. Bow Thruster - Interlocks & Troubleshooting','',7),
  ('T19','s-static','9. Static Electricity - Risks & Prevention','',8),
  ('T19','s-pumproom','10. Pump Room Safety & Light Inspection','',9),
  ('T19','s-gasdetect','11. Gas Detection Systems','',10),
  ('T19','s-misc','12. Auto-Tension, Cargo Hose IR Test, Anti-Heeling','',11),
  ('T19','s-framo','13. Framo Hydraulic Powerpack & Cargo Pumps','',12),
  ('T19','s-updates','14. Tanker Operations & 2026 Updates','',13),
  ('T19','s-surveyorqa','Surveyor Questions & Ideal Answers','',14),
  ('T19','s-quickrev','Quick Revision - Surveyor Frequency Guide','',15),
  ('T20','s-hull','1. Hogging, Sagging, Shear Force & Bending Moment','',0),
  ('T20','s-structure','2. Ship Structure - Bulkheads, Keel & Load Line','',1),
  ('T20','s-framing','3. Framing Systems & Double Bottom','',2),
  ('T20','s-panting','4. Panting & Pounding - Bow Structure','',3),
  ('T20','s-stress','5. Stress, Strain & Fatigue in the Hull','',4),
  ('T20','s-stability','6. Stability - GM, KG, KB, BM & GZ Curve','',5),
  ('T20','s-fse','7. Free Surface Effect (FSE) & Anti-Roll Tanks','',6),
  ('T20','s-cofferdam','8. Cofferdam - Purpose & Electrical Safety','',7),
  ('T20','s-esb','9. Emergency Switchboard (ESB) & Two ACBs','',8),
  ('T20','s-seqstart','10. Sequential Starting After Blackout - Timings & Logic','',9),
  ('T20','s-container','11. Container Ship - CSC Convention & Cargo Fires','',10),
  ('T20','s-drydock','12. Drydock - ETO Electrical Preparations','',11),
  ('T20','s-surveyorqa','13. Surveyor Questions & Ideal Answers','',12),
  ('T20','s-quickrev','14. Quick Revision - Surveyor Frequency Guide','',13),
  ('T21','s-lb-equip','1. Lifeboat Electrical Equipment & ETO Checks','',0),
  ('T21','s-lb-types','2. Lifeboat Types, Carriage & Markings','',1),
  ('T21','s-battery','3. Lifeboat Battery - Specs, Ordering & Commissioning','',2),
  ('T21','s-batt-room','4. Battery Room - Safeties & SOLAS','',3),
  ('T21','s-engine','5. Lifeboat Engine & Electrical Starting Circuit','',4),
  ('T21','s-davit','6. Davit Safety Devices & Release Mechanisms','',5),
  ('T21','s-rescue','7. Rescue Boat','',6),
  ('T21','s-liferaft','8. Liferaft, HRU & Weak Link','',7),
  ('T21','s-pyro','9. Pyrotechnics','',8),
  ('T21','s-immersion','10. Immersion Suit, TPA & Lifejacket','',9),
  ('T21','s-eebd','11. EEBD & SCBA','',10),
  ('T21','s-embark','12. Embarkation Lighting, Embarkation Ladder & MOB','',11),
  ('T21','s-epirb-sart','13. EPIRB & SART - Electrical Details','',12),
  ('T21','s-updates','14. LSA Updates & Amendments (2026 and Beyond)','',13),
  ('T21','s-surveyorqa','Surveyor Questions & Ideal Answers','',14),
  ('T21','s-quickrev','Quick Revision - Surveyor Frequency Guide','',15),
  ('T22','s-etofundamentals','1. ETO Fundamentals Quick-Fire Drill','',0),
  ('T22','s-duties','2. ETO Duties, Routines & PMS','',1),
  ('T22','s-drydock','3. Drydock ETO Duties','',2),
  ('T22','s-coldiron','4. Cold Ironing - Shore Power Connection','',3),
  ('T22','s-wrongway','5. Wrong Way Alarm','',4),
  ('T22','s-blackout','6. Blackout Recovery & Testing','',5),
  ('T22','s-permits','7. Permit to Work - Electrical & General Safety','',6),
  ('T22','s-shocktreatment','8. Electric Shock - Current Effects & Treatment','',7),
  ('T22','s-enclosedspace','9. Enclosed Space Entry','',8),
  ('T22','s-welding','10. Welding Safety & Crane Safeties','',9),
  ('T22','s-boiler','11. Boiler Burner Management & VRCS','',10),
  ('T22','s-cableorder','12. Cable Ordering Specifications','',11),
  ('T22','s-troubleshoot','13. Troubleshooting, Diagnostics & 6-Step Framework','',12),
  ('T22','s-imosymbols','14. IMO Safety Symbols & Signs','',13),
  ('T22','s-emergencydrills','15. Emergency Drills - ETO Muster Duties','',14),
  ('T22','s-diagnostics','16. Advanced Diagnostics & Measurements','',15),
  ('T22','s-surveyorqa','Surveyor Questions & Ideal Answers','',16),
  ('T22','s-quickrev','Quick Revision - Surveyor Frequency Guide','',17),
  ('T23','s-fundamentals','1. Cell Fundamentals - Primary vs Secondary','',0),
  ('T23','s-rating','2. Battery Ratings - Ah, C-Rate & CCA','',1),
  ('T23','s-leadacid','3. Lead-Acid vs NiCd - Full Comparison','',2),
  ('T23','s-vrla','4. VRLA Batteries - Sealed, AGM & Gel Types','',3),
  ('T23','s-charger','5. Battery Charger - Three Charging Stages','',4),
  ('T23','s-equalise','6. Equalising Charge - Purpose & Procedure','',5),
  ('T23','s-sg','7. SG Measurement, Values & Temperature Correction','',6),
  ('T23','s-alkaline','8. Alkaline & Primary Cells','',7),
  ('T23','s-ordering','9. Battery Ordering Specification','',8),
  ('T23','s-solas','10. SOLAS Acceptance Rule - 50% Capacity Test','',9),
  ('T23','s-room','11. Battery Room Safety Requirements','',10),
  ('T23','s-segregation','12. Lead-Acid & NiCd Segregation - Why They CANNOT Share a Room','',11),
  ('T23','s-dc-systems','13. DC Systems Onboard - Applications & Voltage Levels','',12),
  ('T23','s-dc-fault','14. DC Short Circuit Severity - Why DC Arcs Are Harder to Extinguish','',13),
  ('T23','s-ups','15. UPS Battery Systems','',14),
  ('T23','s-lithium','16. Lithium-Ion Batteries & ESS - Safety (Post-2023 Critical)','',15),
  ('T23','s-liion-detail','17. Li-Ion ESS - Off-Gas Chemistry, Detection & BMS','',16),
  ('T23','s-surveyorqa','Surveyor Questions & Ideal Answers','',17),
  ('T23','s-quickrev','Quick Revision - Surveyor Frequency Guide','',18)
ON CONFLICT (topic_id, sort_order) DO NOTHING;

-- ── Verify ────────────────────────────────────────────────────────────────
SELECT count(*) AS total,
       count(*) FILTER (WHERE url <> '') AS with_url,
       count(DISTINCT topic_id) AS topics
  FROM public.topic_videos;
