/* GENERATED by _counts.cjs on 2026-08-22 - do not edit by hand.
   Counted from the encrypted content itself, so these cannot drift from
   what the app actually loads. Regenerate after adding content:
     CONTENT_KEY_ORAL=... CONTENT_KEY_WRITTEN=... node _counts.cjs  */
window.EB_COUNTS = {
  oralTopics: 23,
  writtenTopics: 8,
  numericals: 39,
  quizQuestions: 5861,
  surveyorQuestions: 1193,
  surveyors: 54,
  generatedOn: '2026-08-22'
};
